generator:
  class: sfPropelGenerator
  param:
    model_class:           item
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              item
    plural:                items
    route_prefix:          item
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Menu items
      filter:
        display: [label, description, test_container_id]
      form:    ~
      edit:
        title: Editing menu "%%label%%"
      new:
        title: New menu item
